# Generated by Django 4.0 on 2022-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
